version: "3.3"

services:
  db:
    image: redis:7.0
    container_name: chat-redis
    ports:
      - "6379:6379"
  web:
    image: fastapi_redis_chat
    container_name: chat-web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
